### ISSUE TITLE
Core end points to implement for `api`

### ISSUE THREAD

**Issue by SimonGoring** [NeotomaDB/api_nodetest#21]
The original ASP.NET file is located in the [Neotoma BitBucket account](https://bitbucket.org/cei/neotomawsdata/src/a4267aed5fa2b144f8d4c887514104deebdbfe28/GetRequestHandler.vb?at=default&fileviewer=file-view-default)

From what I can figure out there are the following neccessary endpoints for `api.neotomadb.org`:

- [ ] Chronology - See Issue #2
- [ ] Contacts - See issue #3
- [ ] Occurrence - See issue #4
- [ ] Pollen - See issue #5
- [ ] Publications - See issue #6
- [ ] Taxa - See issue #7
- [ ] Sites - see issue #8
- [ ] Datasets - see issue #9
- [ ] Site - see issue #10
- [ ] DownloadZip - see issue #11 (commented out, so likely deprecated)
- [ ] DownloadMultiple - see issue #12
- [ ] DownloadMultipleCSV - See issue #13
- [ ] Downloads - See issue #14
- [ ] DownloadsCSV - See issue #15
- [ ] SampleData - See issue #16
- [ ] GeoPoliticalUnits - See issue #17
- [ ] RollUpChrons_beforeNullControlFix - See issue #18
- [ ] RollUpChrons - see issue #19
- [ ] CheckParameters - See issue #20

**Comment by stryker-m** [comment]
This should read "neccessary endpoints for api.neotomadb.org/v1/data". 
There are additional endpoints at api.neotomadb.org/v1/dbtables and api.neotomadb.org/v1/apps
