### ISSUE TITLE
Core api endpoints to implement for NeotomaExplorer

### ISSUE THREAD

**Issue by stryker-m** [NeotomaDB/api_nodetest#38]
The original ASP.NET projects are located at [Neotoma BitBucket Data](https://bitbucket.org/cei/neotomawsdata/), [Neotoma BitBucket Apps](https://bitbucket.org/cei/neotomawsapps/), and [Neotoma BitBucket DBTables](https://bitbucket.org/cei/neotomawsdbtables/).

These APIs are called by NeotomaExplorer
- [ ] Publications - See Issue #6 
- [ ] Datasets - See issue #9 
- [ ] Downloads - See issue #14 
- [ ] GeoPoliticalUnits - See issue #17 
- [ ] RelativeAgeScales - See issue #22 
- [ ] TaxaInDatasets - See issue #23 
- [ ] TaxaGroupTypes - see issue #24 
- [ ] DatasetTypes- see issue #26 
- [ ] CollectionTypes - see issue #28 
- [ ] Keywords - see issue #29 
- [ ] AuthorPIs - see issue #30 
- [ ] TaphonomySystems - See issue #31 
- [ ] Search - See issue #32 
- [ ] GetDatasetTopTaxaData - See issue #33 
- [ ] ConstituentDatabases - See issue #34 
- [ ] Chronologies - See issue #35 
- [ ] CollectionTypes - See issue #37 
- [ ] MapServer species ranges
- [ ] MapServer ice extent
